import Head from 'next/head';
import { useState } from 'react';
// import Image from 'next/image';

import { LoginIcon, Products, SearchIcon, WishlistsIcon } from '../src/_components';
import { Footer, Navbar } from '../src/_navigation';

export default function Home() {
  const [switchToMap, setSwitchToMap] = useState(false);

  return (
    <div className="position-relative">
      <Head>
        <title>Vacation Homes & Condo Rentals - Airbnb - Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" sizes="192x192" href="https://a0.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png" />
        <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Airbnb" />
        <link rel="apple-touch-icon" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-76x76-3b313d93b1b5823293524b9764352ac9.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-120x120-52b1adb4fe3a8f825fc4b143de12ea4b.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-152x152-7b7c6444b63d8b6ebad9dae7169e5ed6.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="https://a0.muscache.com/airbnb/static/icons/apple-touch-icon-180x180-bcbe0e3960cd084eb8eaf1353cf3c730.png" />
        <meta property="og:url" content="https://www.airbnb.com/" />
        <meta property="og:title" content="Airbnb: Vacation Rentals, Cabins, Beach Houses, Unique Homes &amp; Experiences" />
        <meta property="og:description" content="Find vacation rentals, cabins, beach houses, unique homes and experiences around the world - all made possible by hosts on Airbnb." />
        <meta property="og:type" content="website"></meta>
      </Head>

      <Navbar />

      <main className="">
        <Products switchToMap={switchToMap} setSwitchToMap={setSwitchToMap} />
      </main>

      <div className="forMobileView">
        <button className="explore">
          <SearchIcon />
          <span className="">Explore</span>
        </button>
        <button className="wishlists">
          <WishlistsIcon />
          <span className="">Wishlists</span>
        </button>
        <button className="login">
          <LoginIcon />
          <span className="">Log in</span>
        </button>
      </div>
      {!switchToMap && <Footer />}
    </div>
  )
}
